### ISSUE TITLE
Firebase DataLogging

### ISSUE THREAD

**Issue by SMLM42** [luvkylo/signed#12]
Currently blocked because we need to have user sign-ins and get the search function working

**Comment by luvkylo** [comment]
[https://firebase.google.com/docs/auth/web/google-signin](url)

1. enable google sign-in in Firebase console
2. Create an instance of the Google provider object (step 1 in doc)
3. Authenticate with Firebase using the Google provider object (step 5 in doc) - To sign in with a pop-up window
4. give google access token and signed-in user info
5. (what to do with Google access token)?
6. check if firebase has user - if not we append user and create node favorite
7. refresh the page with maps and all unsigned artist
8. switch label to fav button with click function. Create a favorite list button and a sign-out button (`firebase.auth().signOut().then(function() {
  // Sign-out successful.
}).catch(function(error) {
  // An error happened.
});`)
9. When fav-list button is clicked, empty the table and call the user's favorite node on firebase. parse through all child and append to table. Instead of fav-button, switch to unfav-button with function
